#!/bin/bash

DOMAIN=$1
PORT=$2

function congrats {
	i=0
	while IFS= read -r line; 
	do
		if [ $i == 3 ]; then
			Port=$line
		fi
		(( i++ ))
	done <.env

	printf '%s%s\n' "http://localhost:" "$PORT";
	printf '%s%s\n' "http://$DOMAIN.test:" "$PORT";
	echo "Awesome! you did it..."
	echo 
	echo 
	printf '%s %s\n' "Author:" "Keramot UL Islam <https://abmsourav.com>";
	printf '%s %s' "Developed by CodesVault" "<https://github.com/CodesVault>";
	echo 
}
