#!/bin/bash

DOMAIN=$1

function docker_environment {
	cd `pwd`/$DOMAIN
	echo 
	echo "Starting Docker setup..."
	echo 

	mkdir -m 777 db
	echo "Changing folder mod, may require sudo password.."
	if [ `uname` != 'Darwin' ]; then
		sudo chown -R $User:$User db
		exit
	fi

	docker-compose up -d --build

	if [ `uname` != 'Darwin' ]; then
		sudo chown -R $User:$User db
	fi
	sudo chmod -R 777 db
}
