#!/bin/bash

DOMAIN=$1

function docker_environment {
	cd `pwd`/$DOMAIN
	echo 
	echo "Starting Docker setup..."
	echo 

	mkdir -m 777 db
	echo "Changing folder mod, may require sudo password.."
	sudo chown -R $User:www-data db

	docker-compose up -d --build

	sudo chown -R $User:www-data db
	sudo chmod -R 777 db
}