#!/bin/bash

function get_inputs {
	read -p "Domain prefix: " DOMAIN
	if [ ! $DOMAIN ]; then
		printf "*** Domain prefix is required. \nExit\n"
		exit
	fi

	PHP_VERSION=7.4
	read -p "PHP version: [Default  7.4]  " php_version
	if [ $php_version ]; then
		PHP_VERSION=$php_version
	fi

	NODEJS_VERSION=16.x
	read -p "NodeJS version: [Default 16.x] " nodejs_version
	if [ $nodejs_version ]; then
		NODEJS_VERSION=$nodejs_version
	fi
}
