#!/bin/bash

check_os() {
	OS="`uname`"
	Extension='.zip'

	if [ $OS == "Darwin" ]; then
		Extension=".tar.gz"
	fi
}

function prepare_wp {
	if [ `uname` != 'Darwin' ]; then
		sudo chown -R $User:$User wordpress
	fi
	sudo chmod -R 777 wordpress

	echo 
	read -p "Want to download WordPress also? (y/N): " Download_WP
	if [ $Download_WP == "N" ]; then
		exit
	fi

	check_os

	wp_version=latest
	read -p "WordPress Version: [Default: latest] " WP_Version
	if [ $WP_Version ]; then
		wp_version=$WP_Version
	fi
	if [ $wp_version != "latest" ]; then
		wp_version="wordpress-$WP_Version"
	fi

	echo 
	echo "Downloading WordPress $wp_version ..."
	curl -sS -o wp$Extension https://wordpress.org/$wp_version$Extension

	echo "Changing folder mod, may require sudo password.."
	if [ `uname` != 'Darwin' ]; then
		sudo chown $User:$User wp$Extension
	fi
	sudo chmod 777 wp$Extension

	echo "Unzipping..."
	if [ `uname` != 'Darwin' ]; then
		unzip -q wp$Extension
	fi
	if [ `uname` == 'Darwin' ]; then
		tar -xf wp$Extension
	fi

	echo 
	if [ `uname` != 'Darwin' ]; then
		sudo chown -R $User:$User wordpress
	fi
	sudo chmod -R 777 wordpress

	rm -rf wp$Extension
	echo "Done."
}
