version: '3.0'

networks:
  default:
    name: ${APP}

services:
  web:
    build:
      context: .
      dockerfile: ./configs/nginx.dockerfile
    container_name: ${APP}_web
    depends_on:
      - php
      - mysql
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated
    ports:
      - ${HTTP_PORT}:80

  mysql:
    image: mysql:latest
    container_name: ${APP}_mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./configs/app.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - NODEJS_VERSION=${NODEJS_VERSION}
    container_name: ${APP}_php
    volumes:
      - ./configs/php.ini:/usr/local/etc/php/php.ini
      - ./wordpress:/var/www/html:delegated
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}